name: 'candidates_results_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["data_models"]
test-paths: ["tests"]
seed-paths: ["datasets_in_csv_input_seed"]
macro-paths: ["dbt_jinja_macros"]
packages-install-path: "/usr/dbt_modules"

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

    
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.