version: "3"
services:
  dbt:
    tty: true
    image: dbt-candidates
    build: .
    working_dir: /usr/app/
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.dbt/gbq_creds.json
    volumes:
      - .:/usr/app/
      - ./conf/.dbt/:/root/.dbt/
