default:
  target: test
  outputs:
    test:
      type: bigquery
      method: service-account
      database: qalearn
      schema: test
      threads: 7
      timeout_seconds: 300
      priority: interactive
      keyfile: /root/.dbt/gbq_creds.json

    dbt_transform:
      type: bigquery
      method: service-account
      database: qalearn
      schema: dbt_transform_final_candidates
      threads: 7
      timeout_seconds: 300
      priority: interactive
      keyfile: /root/.dbt/gbq_creds.json